INSERT INTO BUILDING(ID, NAME) VALUES (-100, 'Espace Fauriel');
INSERT INTO BUILDING(ID, NAME) VALUES (-99, '158');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1, -100);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1, -100);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-8, 'Room3', 1, -99);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-3, 5, 'OFF', -8);